#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the xbot usb connection as /dev/xbot."
echo ""

sudo cp `rospack find xbot_ftdi`/50-xbot.rules /etc/udev/rules.d


echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart

